<Project>
  <PropertyGroup>
    <DotNetVer>net8.0</DotNetVer>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <IncludeSorceReevisionInInformationalVersion>false</IncludeSorceReevisionInInformationalVersion>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <ExecutableAssemblyName>myavalonia</ExecutableAssemblyName>
    <ApplicationTitle>My Avalonia</ApplicationTitle>
    <Company>Company</Company>
    <Product>Product</Product>
    <Description>Description</Description>
    <AssemblyTitle>AssemblyTitle</AssemblyTitle>
    <ProductVersion>0.1.0.0</ProductVersion>
    <Copyright>Copyright</Copyright>
    <FileVersion>$(ProductVersion)</FileVersion>
    <AssemblyVersion>$(FileVersion)</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaNameGeneratorAttachDevTools>false</AvaloniaNameGeneratorAttachDevTools>
  </PropertyGroup>

</Project>